export { default as Header } from './Header/Header';
export { default as ExtraHeaderSection } from './ExtraHeaderSection/ExtraHeaderSection';
export { default as SectionHeading } from './SectionHeading/SectionHeading';
export { default as Services } from './Services/Services';
export { default as ProjectCount } from './ProjectCount/ProjectCount';
export { default as Pricing } from './Pricing/Pricing';
export { default as Testimonial } from './Testimonial/Testimonial';
export { default as ContactForm } from './Contact/ContactForm';
export { default as Footer } from './Footer/Footer';